import fs from "node:fs/promises";
import { execSafe as exec, execOrThrow } from "./exec.js";
import { isPortFree } from "./net.js";
import { proxyComposeFile, proxyDir } from "./paths.js";
import type { Config } from "../types.js";

export const PROXY_PROJECT = "easy-worktree-proxy";

export class PortUnavailableError extends Error {
  constructor(
    readonly port: number,
    /** True when a plain socket probe said the port was free - Windows does this. */
    readonly looksFree: boolean,
  ) {
    super(
      `Docker cannot publish port ${port}.` +
        (looksFree
          ? ` A socket probe says it is free, so this is a Windows-level reservation ` +
            `(Hyper-V/WinNAT) that only affects Docker.`
          : ` Something else is listening on it.`) +
        ` Set [proxy] port = <n> in worktree.toml - URLs will then include the port.`,
    );
    this.name = "PortUnavailableError";
  }
}

/**
 * The one published port on the whole machine. Everything else reaches the
 * outside world through here, keyed by Host header.
 *
 * `providers.docker.network` matters: worktree services sit on two networks
 * (their private one and the shared proxy one), and without this Traefik may
 * pick the private address it cannot reach.
 */
function proxyCompose(config: Config): string {
  return `# Generated by git-grove. Edits will be overwritten.
name: ${PROXY_PROJECT}

services:
  traefik:
    image: ${config.proxy.image}
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=${config.proxy.network}
      - --entryPoints.web.address=:80
      - --log.level=INFO
    ports:
      - "${config.proxy.port}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - wt.managed=true

networks:
  proxy:
    name: ${config.proxy.network}
    external: true
`;
}

export interface ProxyStatus {
  running: boolean;
  port: number;
  network: string;
}

async function networkExists(name: string): Promise<boolean> {
  const { code, stdout } = await exec("docker", [
    "network",
    "ls",
    "--filter",
    `name=^${name}$`,
    "--format",
    "{{.Name}}",
  ]);
  return code === 0 && stdout.trim().split("\n").includes(name);
}

async function psProxy(format: string): Promise<string | null> {
  const { code, stdout } = await exec("docker", [
    "ps",
    "--filter",
    `label=com.docker.compose.project=${PROXY_PROJECT}`,
    "--filter",
    "status=running",
    "--format",
    format,
  ]);
  if (code !== 0) return null;
  const first = stdout.trim().split("\n")[0]?.trim();
  return first ? first : null;
}

async function proxyRunning(): Promise<boolean> {
  return (await psProxy("{{.ID}}")) !== null;
}

/** Last lines from the running proxy, for diagnosing provider failures. */
export async function proxyLogs(tail = 50): Promise<string[]> {
  const name = await psProxy("{{.Names}}");
  if (!name) return [];
  const { stdout, stderr } = await exec("docker", ["logs", "--tail", String(tail), name]);
  return (stdout + stderr).split("\n").map((l) => l.trimEnd()).filter(Boolean);
}

/**
 * True when Traefik is up but cannot read the Docker socket. Presents as blanket
 * 404s with no other symptom, so it is worth naming explicitly.
 */
export function proxyProviderBroken(logs: string[]): boolean {
  return logs.some((l) =>
    /Failed to retrieve information of the docker client|Provider error/i.test(l),
  );
}

export async function proxyStatus(config: Config): Promise<ProxyStatus> {
  return {
    running: await proxyRunning(),
    port: config.proxy.port,
    network: config.proxy.network,
  };
}

/** Idempotent: creates the shared network and starts Traefik if not already up. */
export async function ensureProxy(config: Config): Promise<ProxyStatus> {
  if (!(await networkExists(config.proxy.network))) {
    await execOrThrow("docker", ["network", "create", config.proxy.network]);
  }

  // Recreate rather than short-circuit when the configured image has changed,
  // otherwise editing [proxy] image appears to do nothing.
  const runningImage = await psProxy("{{.Image}}");
  if (runningImage !== null) {
    if (runningImage === config.proxy.image) {
      return { running: true, port: config.proxy.port, network: config.proxy.network };
    }
    await stopProxy();
  }

  // Advisory only. A socket probe is not authoritative in either direction:
  // Windows can reserve a port such that Docker's bind fails while a plain
  // Node listen on 0.0.0.0 succeeds. Docker is the authority, so we let it try
  // and translate its refusal below.
  const looksFree = await isPortFree(config.proxy.port);

  await fs.mkdir(proxyDir(), { recursive: true });
  await fs.writeFile(proxyComposeFile(), proxyCompose(config), "utf8");

  const result = await exec("docker", [
    "compose",
    "-f",
    proxyComposeFile(),
    "-p",
    PROXY_PROJECT,
    "up",
    "-d",
  ]);

  if (result.code !== 0) {
    const output = `${result.stderr}\n${result.stdout}`;
    if (/ports are not available|address already in use|Only one usage/i.test(output)) {
      throw new PortUnavailableError(config.proxy.port, looksFree);
    }
    throw new Error(
      `Could not start the proxy:\n${output.trim().split("\n").slice(-6).join("\n")}`,
    );
  }

  return { running: true, port: config.proxy.port, network: config.proxy.network };
}

export async function stopProxy(): Promise<void> {
  await exec("docker", ["compose", "-f", proxyComposeFile(), "-p", PROXY_PROJECT, "down"]);
}
