import { envKey } from "../naming.js";
import type { Decision, Decisions } from "./decide.js";

/**
 * Decisions in, files out. No model, no I/O, no clock — the same decisions always
 * render byte-identical output, which is what makes this testable at all.
 */
export interface Rendered {
  overlay: { file: string; content: string };
  config: { file: string; content: string };
}

export const OVERLAY_FILE = "docker-compose.worktree.yml";
export const CONFIG_FILE = "worktree.toml";

export function render(decisions: Decisions): Rendered {
  return {
    overlay: { file: OVERLAY_FILE, content: renderOverlay(decisions) },
    config: { file: CONFIG_FILE, content: renderConfig(decisions) },
  };
}

/**
 * The overlay is always a NEW file applied with `-f base -f overlay`; the base
 * file is never touched.
 *
 * That buys two things worth more than they look: there is no comment- or
 * formatting-preserving YAML round-trip to get wrong, and a bad generation is one
 * deletable file rather than a repo-wide diff to unpick. Plain `docker compose
 * up` also keeps working for anyone not using worktrees.
 */
export function renderOverlay(decisions: Decisions): string {
  const out: string[] = [
    "# Generated by `wt adapt render`. Applied on top of the base compose file,",
    "# which is never modified — plain `docker compose up` still works.",
    "#",
    "#   ports: !reset []   cancels the base file's published ports (Compose >= 2.24)",
    "#   ports: !override   REPLACES them. `!reset` erases the key and ignores any",
    "#                      value you give it, so `!reset [\"${WT_PORT_DB}:5432\"]`",
    "#                      publishes nothing at all.",
    "#   *.internal alias   unambiguous name for sibling calls — a bare `api` is",
    "#                      ambiguous on the shared proxy network, where every",
    "#                      worktree has one.",
    "services:",
  ];

  for (const svc of decisions.services) {
    out.push(`  ${svc.name}:`);
    out.push(...renderPorts(svc));
    out.push(...renderEnvironment(svc));
    out.push(...renderNetworks(svc));
    out.push(...renderLabels(svc));
    out.push("");
  }

  out.push("networks:");
  out.push("  internal:");
  out.push("  wt-proxy:");
  out.push("    external: true");
  out.push("    name: ${WT_PROXY_NETWORK}");

  return out.join("\n") + "\n";
}

function renderPorts(svc: Decision): string[] {
  if (!svc.hostPort) {
    // Every published port has to go, or two worktrees collide on the host — the
    // entire problem this tool exists to solve.
    return ["    ports: !reset []"];
  }
  return [
    "    # Not HTTP, so the proxy cannot front it: it keeps a real host port,",
    "    # leased per worktree instead of hardcoded.",
    "    ports: !override",
    `      - "\${WT_PORT_${envKey(svc.name)}}:${svc.containerPort}"`,
  ];
}

function renderEnvironment(svc: Decision): string[] {
  const entries = Object.entries(svc.envRewrites).sort(([a], [b]) => a.localeCompare(b));
  const out = ["    environment:"];
  for (const [key, value] of entries) out.push(`      ${key}: ${value}`);
  // Lets the app report which worktree served a request, which is how an e2e test
  // proves it reached the right stack rather than a sibling's.
  out.push("      WT_NAME: ${WT_NAME}");
  return out;
}

function renderNetworks(svc: Decision): string[] {
  const out = ["    networks:", "      internal:", "        aliases:", `          - ${svc.name}.internal`];
  // Only services with ingress join the shared network; the rest stay private,
  // which keeps the shared network's namespace as uncrowded as possible.
  if (svc.subdomain) out.push("      wt-proxy: {}");
  return out;
}

function renderLabels(svc: Decision): string[] {
  const out = ["    labels:"];
  if (svc.subdomain && svc.containerPort !== null) {
    const router = `\${WT_NAME}-${svc.name}`;
    out.push("      - traefik.enable=true");
    out.push(
      `      - traefik.http.routers.${router}.rule=Host(\`${svc.subdomain}.\${WT_NAME}.\${WT_DOMAIN}\`)`,
    );
    out.push(`      - traefik.http.services.${router}.loadbalancer.server.port=${svc.containerPort}`);
  }
  // What `wt gc` sweeps by. Without it an orphaned container is invisible.
  out.push("      - wt.managed=true");
  return out;
}

export function renderConfig(decisions: Decisions): string {
  const out: string[] = [
    "# Generated by `wt adapt render`. Edit freely — this file is yours.",
    "[project]",
    `name = ${toml(decisions.project)}`,
    `compose = [${[...decisions.composeFiles, OVERLAY_FILE].map(toml).join(", ")}]`,
    "",
    "[domain]",
    "# localtest.me is real public DNS with a wildcard pointing at 127.0.0.1.",
    "# *.localhost is NOT resolvable by the Windows resolver, curl, or Node fetch.",
    `suffix = ${toml(decisions.domain)}`,
    "",
    "[proxy]",
    "# 80 gives the cleanest URLs, but Docker Desktop often holds it even with no",
    "# containers running. Any port works; URLs then carry it.",
    `port = ${decisions.proxyPort}`,
    "",
  ];

  for (const svc of decisions.services) {
    out.push("[[services]]");
    out.push(`name = ${toml(svc.name)}`);
    out.push(`layer = ${toml(svc.layer)}`);
    if (svc.subdomain) out.push(`subdomain = ${toml(svc.subdomain)}`);
    // `port` here means "the HTTP port behind the proxy", and it is what
    // `internalUrl` is built from. Emitting it for a database would advertise
    // `http://db.internal:5432`, which is a lie a consumer would act on.
    if (svc.subdomain && svc.containerPort !== null) out.push(`port = ${svc.containerPort}`);
    if (svc.hostPort) out.push("host_port = true");
    const health = renderHealth(svc.health);
    if (health) out.push(`health = ${health}`);
    if (svc.confidence !== "high") {
      out.push(`# ${svc.confidence} confidence: ${svc.evidence}`);
    }
    out.push("");
  }

  const groups = buildGroups(decisions.services);
  if (Object.keys(groups).length > 0) {
    out.push("[groups]");
    for (const [name, members] of Object.entries(groups)) {
      out.push(`${name} = [${members.map(toml).join(", ")}]`);
    }
    out.push("");
  }

  const dbEnv = databaseUrl(decisions.services);
  if (dbEnv) {
    out.push("# Interpolated against the vars `wt run` injects.");
    out.push("[env]");
    out.push(dbEnv);
    out.push("");
  }

  if (decisions.review.length > 0) {
    out.push("# Review before trusting this file:");
    for (const note of decisions.review) out.push(`#   - ${note}`);
    out.push("");
  }

  return out.join("\n");
}

function renderHealth(health: Decision["health"]): string | null {
  if (health === null) return null;
  if (typeof health === "string") return toml(health);
  if ("tcp" in health) return "{ tcp = true }";
  if (health.exec.length === 0) return null;
  return `{ exec = [${health.exec.map(toml).join(", ")}] }`;
}

/**
 * Groups exist so a caller can start a slice of the stack. `backend` deliberately
 * omits the frontend: a full stack per worktree is expensive, and several are
 * usually running at once.
 */
function buildGroups(services: Decision[]): Record<string, string[]> {
  const groups: Record<string, string[]> = {};
  const backend = services.filter((s) => s.layer !== "frontend").map((s) => s.name);
  const data = services.filter((s) => s.layer === "data").map((s) => s.name);

  if (backend.length > 0 && backend.length < services.length) groups.backend = backend;
  if (data.length > 0 && data.length < services.length) groups.data = data;
  return groups;
}

/**
 * `DATABASE_URL` for a host-reachable database, using the credentials the compose
 * file already declares.
 *
 * The host address is deliberately left as a template: the port is leased per
 * worktree and is only known at run time. This is the value that made the whole
 * design worth building — it is byte-identical in every worktree.
 */
function databaseUrl(services: Decision[]): string | null {
  const db = services.find((s) => s.hostPort && s.layer === "data" && s.database);
  if (!db?.database) return null;
  const { scheme, user, password, name } = db.database;
  return `DATABASE_URL = "${scheme}://${user}:${password}@\${WT_HOST_${envKey(db.name)}}/${name}"`;
}

/** TOML basic string. The inputs here are service names and paths, but escape anyway. */
function toml(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
